add game logic
ey-charles/mv-07-tictactoe pull request #3
Opened 2021-02-19 17:30 UTC by LoxiasCam

### Milestone 3: Game Logic

In this milestone we added working game logic to the game. You can play the game by choosing the cell you want to place your symbol in, for example A1 or C3.

- Added working logic for game flow
- Created classes to handle different aspects of game flow
- User interaction is being handled from main.rb
- Game checks for invalid turns and draw conditions

2021-02-19 18:54 UTC, BrianSammit requested changes
CHANGES REQUIRED :recycle: :red_circle: 
--------------
Hello team!! :wave: Great job working on this milestone :muscle: 
However, there are a few changes to make to complete this milestone :hammer_and_wrench: see them below :point_down: 
--------------

- [ ] No puts/print and gets.chomp outside main.rb file. You have two `p` outside the `main.rb` file. See my inline comments :eyes:  to know where are the `p`. kindly move them to `main.rb`
![only_main_print](https://user-images.githubusercontent.com/64173189/108546269-e6feba80-72b6-11eb-9000-8ab6ecb36292.png)

- [x] No inline comments in this milestone. Remove all your inline comments from the code. See my inline comments :eyes: 
----------------
Make these minor changes :hammer_and_wrench: and send it for another review :muscle: 
HAPPY CODDING!!
![MB5W4D](https://user-images.githubusercontent.com/64173189/108548505-e9aedf00-72b9-11eb-88d2-8b8f65865778.gif)

2021-02-19 18:54 UTC, BrianSammit commented on lib/board.rb
> +  end
In line 17 you have one `p`. Remember that the print/puts must be only on `main.rb`

2021-02-19 18:54 UTC, BrianSammit commented on lib/game.rb
> +  end
In line 19 you have one `p`. Remember that the print/puts must be only on `main.rb`

2021-02-19 18:54 UTC, BrianSammit commented on bin/main.rb
> +# initialize game
Remove the inline comment from line 11.

2021-02-19 18:54 UTC, BrianSammit commented on lib/game.rb
> +    # max. number of players is 2
Remove the comment from line 12.

2021-02-19 18:54 UTC, BrianSammit commented on lib/game.rb
> +  # Check if game has a winner
Remove the comment from line 27.

2021-02-19 18:54 UTC, BrianSammit commented on lib/game.rb
> +  # Returns: boolean
Remove the comments from lines 39 and 40.

2021-02-20 00:55 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello Camilo Patino Alzate & Carlos Castillo Velasquez ** 
Nice job with your first submission for this project :muscle:  :muscle:
Your game is already working perfectly :clap: :clap: :clap:  
There are just a few details to improve in your code before you can go ahead:

- [x] Fix rubocop offenses
- [x] Whenever there is a winner, display the winner's name
- [x] Validate player1 and player2 have different names
- [x] Validate player's name is never an empty string
- [x] In Player class, name and token attribute don't need the attr_accessor since they are never written outside the class.
- [ ] In Board class, grid attribute doesn't need the attr_reader since it is never read outside the class.
- [ ] In Game class, set_winner should be removed if not used, or it should be private if it is never called outside the class.
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

2021-02-20 09:55 UTC, bini-i approved these changes
# Status: Approved :heavy_check_mark:
### Hello  @LoxiasCam and @ey-charles :wave: 
### Very nice project. Thank you for working on the suggested changes and the project is approved :tada:
#### You can now merge this pull request and continue to the next milestone.

#### If you have any question kindly reach me on slack @Binyam Hailemeskel

### HAPPY CODING :computer: :blush: 

> #### Reviewed by Binyam Hailemeskel (TSE)
> GitHub: [@bini-i](https://github.com/bini-i)
> Twitter: [@binyamshewa](https://twitter.com/binyamshewa)
> LinkedIn: [LinkedIn](https://www.linkedin.com/in/binyam-hailemeskel-728048151/)

2021-02-20 12:29 UTC, merged